name: Combine PRs

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
  workflow_dispatch:

permissions:
  contents: write

jobs:
  combine-prs:
    runs-on: ubuntu-latest

    if: github.event_name == 'workflow_dispatch' || github.actor == 'dependabot[bot]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Combine PRs
        uses: github/combine-prs@v5.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch_prefix: 'dependabot'
          combine_branch_name: 'combined-dependabot-prs'
          pr_title: 'Combined Dependabot PRs'
          pr_body_header: '# Combined Dependabot PRs'
          min_combine_number: 2
          ci_required: true
          review_required: false
          ignore_label: 'nocombine'
          autoclose: true
          update_branch: true
