name: Combine PRs

on:
  schedule:
    - cron: '0 2 * * 0' # Runs every Sunday at 2 AM
  workflow_dispatch: # Allows manual triggering

jobs:
  combine-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Combine PRs
        uses: github/combine-prs@v5.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch_prefix: 'dependabot'
          combine_branch_name: 'combined-dependabot-prs'
          pr_title: 'Combined Dependabot PRs'
          pr_body_header: '# Combined Dependabot PRs'
          min_combine_number: 2
          ci_required: true
          review_required: false
          ignore_label: 'nocombine'
          autoclose: true
          update_branch: true
