name: Merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - dependabot
  workflow_dispatch:

jobs:
  merge-dependabot-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    # Add a condition to check the PR author
    if: |
      github.event_name == 'workflow_dispatch' || # Always run on manual trigger
      github.actor == 'dependabot[bot]' # Only run if the author is dependabot[bot]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: dependabot
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # This step will only run when triggered by a pull_request event AND the author is dependabot[bot]
      - name: Merge Dependabot PR (on PR event)
        if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin pull/${{ github.event.pull_request.number }}/head:${{ github.head_ref }}
          git merge --no-ff ${{ github.head_ref }} -m "Merge Dependabot PR: ${{ github.event.pull_request.title }}"
          git push origin dependabot

      # This step will only run when triggered by workflow_dispatch
      - name: Merge all open Dependabot PRs (on manual trigger)
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          gh pr list --state open --base dependabot --search "author:app/dependabot" --json number,headRefName,title | jq -c '.[]' | while read pr; do
            pr_number=$(echo $pr | jq -r '.number')
            head_ref=$(echo $pr | jq -r '.headRefName')
            pr_title=$(echo $pr | jq -r '.title')
            echo "Attempting to merge PR #$pr_number: $pr_title"
            git checkout dependabot
            git fetch origin pull/$pr_number/head:$head_ref || { echo "Fetch of PR #$pr_number failed. Skipping merge and close."; continue; }
            git merge --no-ff $head_ref -m "Merge Dependabot PR #$pr_number: $pr_title" || { echo "Merge of PR #$pr_number failed. Skipping close."; continue; }
            git push origin dependabot || { echo "Push after merging PR #$pr_number failed. Skipping close."; continue; }
            gh pr close $pr_number || echo "Closing PR #$pr_number failed."
            git branch -d $head_ref || echo "Failed to clean up branch $head_ref."
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # This step will only run when triggered by a pull_request event AND the author is dependabot[bot]
      - name: Close Dependabot PR (on PR event)
        if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
        run: gh pr close ${{ github.event.pull_request.number }} --confirm
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
